### ISSUE TITLE
[Bug] 버그 모음집

### ISSUE THREAD

**Issue by miniposi** [10-rolling/rollingPolling#24]
### 🐞 버그 설명

* Global Style에 font-family 추가

### ✅ 예상 결과

전체 폰트 적용

### ❗ 실제 결과

.

**Comment by oauch** [comment]
![스크린샷 2023-11-10 오후 6 28 15](https://github.com/10-rolling/rollingPolling/assets/49686619/b35d615e-7914-4e13-ab5b-13fed4b68a09)
버튼 클릭하면 밑으로 스타일일이 내려가는 현상
