### ISSUE TITLE
[Bug] arrow down의 망령 제거

### ISSUE THREAD

**Issue by miniposi** [10-rolling/rollingPolling#74]
### 🐞 버그 설명

arrowdown과 arrowDown 뫼비우스의 띠에 갇힘 ...
저 파일들 때문에 pull, push가 되지 않음!@!

### ✅ 예상 결과

깔끔한 push~ pull~
그 외, icons 안의 스타일 맞추기

### ❗ 실제 결과

.

**Comment by hanseulhee** [comment]
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ

**Comment by ngsy** [comment]
어서 퇴치해주세요!! 퇴마사님!!

**Comment by oauch** [comment]
망령 퇴치 작전 👻
